### ISSUE TITLE
Take advantage of returning assignments

### ISSUE THREAD

**Issue by MeWhenI** [polygolf-lang/polygolf#322] opened 2023-12-20 03:25 UTC
Perform transformations like:
```javascript
a=3;b=a*c-a
c++;d*=c
e*=f;f++
```
=>
```javascript
b=(a=3)*c-a
d*=++c
e*=f++
```
This should probably wait for resolution of #272 since this functionality relies on keeping track of the order that assignments are performed in.

**Comment by MichalMarsalek** [comment] 2023-12-20 06:38
Duplicate of #137 .

**Closed by MichalMarsalek** 2023-12-20 06:38 UTC
Labels: enhancement
